services:
  web:
    build: .
    container_name: php-web
    ports:
      - "8085:80"
    volumes:
      - ../examen-php-SergiColl:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: examen_php
      MYSQL_USER: examen
      MYSQL_PASSWORD: examen123
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: alumno
      PMA_PASSWORD: alumno123
    ports:
      - "8083:80"

  browsersync:
    image: node:20-alpine
    container_name: browsersync
    working_dir: /app
    depends_on:
      - web
    volumes:
      - ../examen-php-SergiColl:/src
    command: sh -c "npm install -g browser-sync && browser-sync start --proxy 'web:80' --files '/src/**/*.*' --no-ui --host 0.0.0.0 --port 3000"
    ports:
      - "3002:3000"